service: bootcamp

frameworkVersion: ">=1.1.0 <2.4.0"

provider:
  name: aws
  runtime: python3.7
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*:*"
    - Effect: Allow

      Action:
        - lambda:InvokeFunction
      Resource: "*"
package:
  exclude:
    - .venv/**
    - .git/**
    - __pycache__/** # for python 3.x
    - "*.pyc" # if using python 2.x
    - node_modules/**
plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux

functions:
  getRecipe:
    handler: users/recipeManager.getRecipes
    events:
      - http:
          path: user
          method: get

  # signUpUser:
  #   handler: users/authentication.signUp
  #   timeout: 10
  #   events:
  #     - http:
  #         path: users/signUp
  #         method: post
  #         cors:
  #           origin: 'https://swipeme.in' # <-- Specify allowed origin
  #           allowCredentials: true
  #
  # loginUser:
  #   handler: users/authentication.login
  #   events:
  #     - http:
  #         path: users/login
  #         method: post
  #         cors:
  #           origin: 'https://swipeme.in' # <-- Specify allowed origin
  #           allowCredentials: true
